theme: jekyll-theme-slate
title: Bancos Brasileiros
description: <img src="https://raw.githubusercontent.com/hjnilsson/country-flags/master/svg/br.svg" alt="Brazil flag" style="width: 16px" title="Brazil"> ğŸ¦ ğŸ“‹ Brazilian banks list
show_downloads: true
